
# docker-compose.yml


version: '3.7'
services:
  mongodb_container:
    image: ivanmarban/armhf-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro


volumes:
  mongodb_data_container: